### PR TITLE
Ensure UTF-8 encoding for file reading/writing

### PR DESCRIPTION
**Pull request by leonluc-dev**
This PR changed the way files are opened to make sure they are interpreted/written using UTF-8 encoding.
Previously wap assumed the default encoding of the system (The Windows-1252 ASCII extension for example)

This caused some issues with non-ASCII characters while reading the .wap.yml file and while generating the resulting .toc file(s).
For example while writing Russian addon descriptions: 
`Notes-ruRU: "Простой интерфейс"`

The above text would cause the following error while packaging the addon:
```
Traceback (most recent call last):
  File "d:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python39\Scripts\wap.exe\__main__.py", line 7, in <module>
  File "d:\python\python39\lib\site-packages\wap\__main__.py", line 15, in main
    exit_code = base.main(standalone_mode=False)
  File "d:\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\python\python39\lib\site-packages\wap\commands\package.py", line 46, in package
    config = Config.from_path(config_path)
  File "d:\python\python39\lib\site-packages\wap\config.py", line 347, in from_path
    contents = file.read()
  File "d:\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 481: character maps to <undefined>
```

Forcing the file operations to use UTF-8 avoids these issues.

### CODE REVIEW

**Comment by t-mart** [comment]
Hey, thanks so much for your contribution! Good catch!

I just ran the checks, and there was a failure during the formatting check: It looks like the mixed quotes (single vs double) on the same line are causing the issue, but I'll have to sit down and look at the code to be sure. (Normally, I'd hope contributors could run the checks themselves, but I had to kick it off because of a permissions setting... Will try to fix that for in the future.)

Also, it'd be nice to see a test that exercises this change too. I can work on that when I get a moment.

Are you by chance using wap to work on your addon? Which one? I'm happy someone is maybe getting some value out of this project. Thanks!

**Comment by leonluc-dev** [comment]
I've fixed the mixed quote usage. For a test adding non-ASCII characters (for example, russian or chinese characters) to the test toc file should test this change. I can update the test but I'm not too familiar with the test framework.

I'm using wap to package the following addon: https://www.curseforge.com/wow/addons/strudelstore
Especially with Burning Crusade Classic now being released it got more tedious to manually manage Classic, BCC and Retail addons, so wap is a nice way to do it automatically. 
(Although with the latest release of the addon I'm checking how well the new multi-TOC system that was introduced to WoW recently works)

**Comment by t-mart** [comment]
Was thinking about this problem more. Since this change forces UTF-8 file operations, we also need to handle the case when the file contents are **non-UTF-8**. I'm working on another branch to handle that.

Also, how interesting about the multi-TOC thing! Didn't realize there were updates in that area. I created wap in part to address the inconvenience of TOC files for different WoW versions. I will have to evaluate how wap fits into that new world -- TOC file generation might get removed completely with that better native alternative.

**Comment by t-mart** [comment]
I released a [version 0.9.0](https://pypi.org/project/wow-addon-packager/0.9.0/) that includes this change just now. Update your installation to get it.

Thanks again!

**Comment by leonluc-dev** [comment]
Thanks. I will check it out soon!

While some of the WoW clients now support multi-TOC (with the exception of retail where it will be introduced when 9.1 releases), many addon installers such as Curseforge client don’t support it yet. So i’ll probably still be using wap for a while.

**Pull request merged**
